version: '3.8'

services:
  api_service:
    build: .
    image: api_image
    container_name: api_container
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8000:80
    env_file: .env
    volumes:
      - ./src:/app/src
